name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy_ecr:
    name: Deploy ECR Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./terraform

      - name: Check if ECR Repository Exists
        id: check_repo
        run: |
          if aws ecr describe-repositories --repository-names my-ecr-repo; then
            echo "Repository exists, skipping creation."
            echo "REPO_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Repository does not exist."
            echo "REPO_EXISTS=false" >> $GITHUB_ENV
          fi
        env:
          AWS_DEFAULT_REGION: us-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Terraform Apply (ECR Only)
        if: env.REPO_EXISTS == 'false'
        run: terraform apply -auto-approve -target=module.ecr_repository
        working-directory: ./terraform

  build_and_push_image:
    name: Build and Push Docker Image
    needs: deploy_ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: example
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/my-ecr-repo:$IMAGE_SHA_TAG -f src/Dockerfile src --push
          docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/my-ecr-repo:$IMAGE_TAG -f src/Dockerfile src --push
          aws lambda update-function-code --function-name example-lambda --image-uri $ECR_REGISTRY/my-ecr-repo:$IMAGE_TAG

  deploy_lambda:
    name: Deploy Lambda Function
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply (Rest of Infrastructure)
        run: terraform apply -auto-approve
        working-directory: ./terraform
